name: vvs_core
description: Package usado nos projetos em Flutter da VVS Sistemas
version: 1.3.1

homepage: https://github.com/bernardoveras/vvs_core/vvs_core.dart

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  flutter:
    sdk: flutter
  uuid: ^3.0.6
  equatable: ^2.0.5
  animate_do: ^2.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  flutter_hooks: ^0.18.5+1
  package_info_plus: ^1.4.3+1
  connectivity_plus: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mocktail: ^0.3.0
  faker: ^2.0.0
  flutter_lints: ^1.0.0

flutter: